# Generated by Django 3.1.2 on 2020-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Admission_no', models.IntegerField()),
                ('Student_photo', models.ImageField(upload_to='Profile_Pic')),
                ('Student_name', models.CharField(max_length=50)),
                ('Father_name', models.CharField(max_length=50)),
                ('Mother_name', models.CharField(max_length=50)),
                ('Student_DOB', models.DateField()),
                ('Student_class', models.IntegerField()),
                ('Student_sec', models.CharField(max_length=1)),
                ('Student_Address', models.CharField(max_length=150)),
                ('Student_Phone', models.CharField(max_length=15)),
                ('Student_Email', models.EmailField(max_length=254)),
                ('Student_gender', models.CharField(max_length=15)),
            ],
        ),
    ]
